---
name: Build and push to Docker hub
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: ${{ github.event_name != 'pull_request' }}
          tags: yesimnathan/nathan.chowning.me:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
